// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sales.Infrastructure.EFCore;

#nullable disable

namespace Sales.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(SaleDbContext))]
    [Migration("20230915162133_CreateAndSeedLeadsTable")]
    partial class CreateAndSeedLeadsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sales.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("DisqualificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisqualificationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisqualificationReason")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f90002e7-cb59-49d0-a7ba-3ffef14e1f9a"),
                            CreatedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("20419e47-058b-45ae-adc7-a1da89bb050c"),
                            DisqualificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedRevenue = 73890m,
                            Source = 2,
                            Status = 1,
                            Title = "Et voluptatem sunt."
                        },
                        new
                        {
                            Id = new Guid("004a27ca-30b7-4ca0-8178-6dc2b8df5ec6"),
                            CreatedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("22d84515-5912-489b-b75c-249964f5a278"),
                            DisqualificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstimatedRevenue = 81034m,
                            Source = 2,
                            Status = 2,
                            Title = "Quae et dolorem mollitia repellendus ut."
                        },
                        new
                        {
                            Id = new Guid("f90002e7-cb59-49d0-a7ba-3ffef14e1f9b"),
                            CreatedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("20419e47-058b-45ae-adc7-a1da89bb050c"),
                            Description = "While the Panther received knife and fork with a little scream of laughter. 'Oh, hush!' the Rabbit say, 'A barrowful of WHAT?' thought Alice to herself, (not in a moment to think that proved it at.",
                            DisqualificationDate = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisqualificationReason = 1,
                            EstimatedRevenue = 88782m,
                            Source = 2,
                            Status = 4,
                            Title = "Officia voluptatem et."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
